### ISSUE TITLE
Confusing fork indicator

### ISSUE THREAD

**Issue by skoteskote** [Edgeryders-Participio/babel-reader#11]
Right now when you have two forks they either display a one "1" or a circled one "(1)". This is confusing as it's not clear that you press that one to see other forks. Ideally it should show 1 for the first fork and 2 for the second, or some other way of indicating that there are several forks.

**Comment by skoteskote** [comment]
@aerugo I think this might be a bit urgent as we now have quite a few forks happening (yay!) The current indicator is confusing and this might stop people from reading forks.

**Comment by jims** [comment]
I will be back from a bit of vacation this week so I can fix it then :)

**Comment by jims** [comment]
This means that we establish that "fork #1" is "no fork"?

**Comment by jims** [comment]
I think it might be nicer to maybe use something different, maybe an icon or something to denote the original?

**Comment by skoteskote** [comment]
I think maybe the original can just be "0"? So it's Fork 0 and then fork 1, instead of a selected/unselected "1" as it is right now

**Comment by jims** [comment]
Makes sense :) All the fixes are deployed now. Please check and see if things are behaving as you would like :)

**Comment by skoteskote** [comment]
Yay! It looks great, thanks for the hard work :)
