### ISSUE TITLE
Reader display name and not username of writer

### ISSUE THREAD

**Issue by skoteskote** [Edgeryders-Participio/babel-reader#12]
If a writer has added their real name to their profile (as e.g. SilverRose has), their real name will appear on the reader instead of their username. I think it's better if we only display the username.

**Comment by aerugo** [comment]
This I don’t agree with. Reason being that the username can’t be changed.
And if a writer picks a shitty username they should be able to change it
later. For example, disco has the username disco but has chosen to be
displayed as disco4robot.

**Comment by skoteskote** [comment]
You misunderstand, Disco has the username disco bot is displayed as disco4robot, Jemma Roper has the username Jemma Roper but is displayed as SilverRose, still the reader is displaying Jemma Roper instead of SilverRose for some reason.

**Comment by aerugo** [comment]
Ah, okay. I get in now. Yeah, so not quite. 
SilverRose still has the username SilverRose, but she has set her name to Jemma Roper. disco4robot has the username disco4robot but has set her name to disco. In the reader, the display name is used. I agree that for the purpose of babel, using the username is better.

**Comment by jims** [comment]
So always just show the username? :D
