### ISSUE TITLE
Divider between posts

### ISSUE THREAD

**Issue by skoteskote** [Edgeryders-Participio/babel-reader#13]
The more I use the reader the more problems I have with the lack of divider between posts. I know there are arguments against this, mainly that some posts are a direct continuation of the previous one, and a divider would destroy the illusion of it all being by one writer. In reality, this is very seldom the case. The majority of posts are like small chapters, and would need a divider to be readable. For longer threads, this lack makes the reader very difficult to use. 

I think we should compromise and add a divider that is only a double line break, to indicate that there is a bigger pause. No symbol or line or anything, just a wider space. This is a compromise intended to take both cases into account.

**Comment by skoteskote** [comment]
Hmm, did you add a divider or what happened? I can't see any change on the reader as for now?

**Comment by jims** [comment]
yes i just haven’t deployed yet. I’m gonna fix the 20 post limit thing as
well first

**Comment by skoteskote** [comment]
gotcha! :)
