### ISSUE TITLE
Reader only shows the first 20 posts in a thread

### ISSUE THREAD

**Issue by skoteskote** [Edgeryders-Participio/babel-reader#14]
See for example [this thread](https://bbu.world/t/everything-that-happened-to-me-that-spring-happened-to-me-privately/893/20), in the reader the thread stops at post 20, in the forum there is 3 more replies after that.

**Comment by jims** [comment]
It seems the fix I picked is throttled by the server (i.e. only #n requests per hour or something) which won't cut it. Either we could see if we can remove this limit or I need to add some other way of fetching the posts, which might be a bit involved.

**Comment by jims** [comment]
Alright, thinking about this some more I think we'll just have to fetch all topics in two requests, one with the initial 20 posts and another request with all the rest, and we'll only do request nr 2 if there are missing posts ofc.
