### ISSUE TITLE
Fork not appearing

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/babel-reader#8]
I tried creating a fork from https://bbu.world/t/epidemic/891/11 to https://bbu.world/t/intellectual-property-rights/129.

If I load https://read.babelbetween.us/#/t/129 it shows up, but not if I load https://read.babelbetween.us/#/t/891

**Comment by jims** [comment]
I'm on it :)

**Comment by jims** [comment]
Fixed in https://github.com/Edgeryders-Participio/babel-reader/commit/568649f80c119cb906dc9cddfe2f666dbf32a28e
